help:
	@echo ""
	@echo "Makefile to drive fieldmap analysis"
	@echo ""
	@echo "Dependencies:"
	@echo " - installed python3 fieldmaptrack (lnls-fac github repository)"
	@echo " - installed python3 mathphys (lnls-fac github repository)"
	@echo " - installed python3 numpy/matplotlib/scipy"
	@echo ""
	@echo "Allowed make arguments are those for fma-analysis.py below:"
	@echo ""
	@fma-analysis.py help

%:
	@fma-analysis.py $@
